---
name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run Tests
        env:
          SECRET_KEY: "-"
          POSTGRES_USER: "-"
          POSTGRES_PASSWORD: "-"
          POSTGRES_HOST: "-"
          POSTGRES_DB: "-"
          ALLOWED_HOSTS: "localhost"
          CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
        run: |
          pytest -vv --junitxml=junit/test-results.xml
